apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRoleBinding
metadata:
  name: superuser-global
subjects:
- kind: ServiceAccount
  name: anaconda
  namespace: kubernetes-dashboard
roleRef:
  kind: ClusterRole
  name: superuser
  apiGroup: rbac.authorization.k8s.io

